### ISSUE TITLE
running hello world example doesn't work

### ISSUE THREAD

**Issue by timeyyy** [benwbooth/quick-clojure#8]
```bash
Traceback (most recent call last):
  File "/home/tim/.local/bin/quick", line 287, in <module>
    elif len(sys.argv) > 1 and sys.argv[1] == 'lein': exit_code = lein(*sys.argv[2:])
  File "/home/tim/.local/bin/quick", line 276, in lein
    result = evaluate(code, ns='leiningen.core.main', toplevel=True)
  File "/home/tim/.local/bin/quick", line 183, in evaluate
    raise Exception('Eval returned bad exit status: %s' % (message['status'][0]))
Exception: Eval returned bad exit status: namespace-not-found
```

Leiningen 2.7.1 on Java 1.8.0_171 OpenJDK 64-Bit Server VM

**Comment by timeyyy** [comment]
if i remove the ns keyword in the call to evaluate from the lein function, it works.

**Comment by benwbooth** [comment]
Hi @timeyyy I haven't worked on this code in years. Actually, I had forgotten what it does until I reviewed the readme file! If you want to submit a pull request, I will merge it in. Thanks!
